import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { Button } from './Button';
export function Layout({ children }) {
    const { user, isAuthenticated, logout } = useAuth();
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const isDevMode = import.meta.env.VITE_DISABLE_LOGIN === 'true';
    return (_jsxs("div", { className: `min-h-screen bg-gray-50 ${isDevMode ? 'pt-12' : ''}`, children: [_jsxs("header", { className: "border-b border-gray-200 bg-white", children: [_jsxs("div", { className: "mx-auto flex max-w-6xl items-center justify-between px-4 py-3", children: [_jsx("a", { href: "/games", className: "text-lg font-bold text-gray-900", children: "Portfolio Modeling Game" }), isAuthenticated && user && (_jsxs(_Fragment, { children: [_jsxs("div", { className: "hidden items-center gap-4 sm:flex", children: [_jsx("span", { className: "text-sm text-gray-600", children: user.displayName }), _jsx(Button, { variant: "ghost", size: "sm", onClick: logout, children: "Logout" })] }), _jsx("button", { className: "rounded-lg p-2 text-gray-600 hover:bg-gray-100 sm:hidden", onClick: () => setMobileMenuOpen(!mobileMenuOpen), "aria-label": mobileMenuOpen ? 'Close menu' : 'Open menu', "aria-expanded": mobileMenuOpen, children: mobileMenuOpen ? (_jsx("svg", { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M6 18L18 6M6 6l12 12" }) })) : (_jsx("svg", { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M4 6h16M4 12h16M4 18h16" }) })) })] }))] }), isAuthenticated && user && mobileMenuOpen && (_jsxs("div", { className: "border-t border-gray-100 px-4 py-3 sm:hidden", children: [_jsx("div", { className: "mb-2 text-sm text-gray-600", children: user.displayName }), _jsx(Button, { variant: "ghost", size: "sm", onClick: logout, className: "w-full justify-start", children: "Logout" })] }))] }), _jsx("main", { className: "mx-auto max-w-6xl px-4 py-6 sm:py-8", children: children })] }));
}
